# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ciphers.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CiphersDialog(object):
    def setupUi(self, CiphersDialog):
        CiphersDialog.setObjectName("CiphersDialog")
        CiphersDialog.resize(869, 496)
        self.gridLayout = QtWidgets.QGridLayout(CiphersDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(CiphersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(CiphersDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.IPATab = QtWidgets.QWidget()
        self.IPATab.setMinimumSize(QtCore.QSize(0, 375))
        self.IPATab.setObjectName("IPATab")
        self.groupBox_1 = QtWidgets.QGroupBox(self.IPATab)
        self.groupBox_1.setGeometry(QtCore.QRect(330, 0, 341, 421))
        self.groupBox_1.setObjectName("groupBox_1")
        self.IPAConsTableWidget = QtWidgets.QTableWidget(self.groupBox_1)
        self.IPAConsTableWidget.setGeometry(QtCore.QRect(10, 20, 321, 391))
        self.IPAConsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.IPAConsTableWidget.setObjectName("IPAConsTableWidget")
        self.IPAConsTableWidget.setColumnCount(3)
        self.IPAConsTableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAConsTableWidget.setItem(11, 2, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.IPATab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 150, 331, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.IPAVowsTableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.IPAVowsTableWidget.setGeometry(QtCore.QRect(10, 20, 311, 241))
        self.IPAVowsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.IPAVowsTableWidget.setObjectName("IPAVowsTableWidget")
        self.IPAVowsTableWidget.setColumnCount(3)
        self.IPAVowsTableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IPAVowsTableWidget.setItem(6, 0, item)
        self.groupBox_3 = QtWidgets.QGroupBox(self.IPATab)
        self.groupBox_3.setGeometry(QtCore.QRect(670, 0, 171, 421))
        self.groupBox_3.setObjectName("groupBox_3")
        self.IPASheetTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.IPASheetTextEdit.setGeometry(QtCore.QRect(10, 20, 151, 391))
        self.IPASheetTextEdit.setReadOnly(True)
        self.IPASheetTextEdit.setObjectName("IPASheetTextEdit")
        self.IPADesc = QtWidgets.QTextBrowser(self.IPATab)
        self.IPADesc.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.IPADesc.setObjectName("IPADesc")
        self.tabWidget.addTab(self.IPATab, "")
        self.KeyTab = QtWidgets.QWidget()
        self.KeyTab.setObjectName("KeyTab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.KeyTab)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 0, 341, 421))
        self.groupBox_4.setObjectName("groupBox_4")
        self.KeyConsTableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.KeyConsTableWidget.setGeometry(QtCore.QRect(10, 20, 321, 391))
        self.KeyConsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.KeyConsTableWidget.setObjectName("KeyConsTableWidget")
        self.KeyConsTableWidget.setColumnCount(3)
        self.KeyConsTableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyConsTableWidget.setItem(11, 2, item)
        self.KeyDesc = QtWidgets.QTextBrowser(self.KeyTab)
        self.KeyDesc.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.KeyDesc.setObjectName("KeyDesc")
        self.groupBox_5 = QtWidgets.QGroupBox(self.KeyTab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 150, 331, 271))
        self.groupBox_5.setObjectName("groupBox_5")
        self.KeyVowsTableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.KeyVowsTableWidget.setGeometry(QtCore.QRect(10, 20, 311, 241))
        self.KeyVowsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.KeyVowsTableWidget.setObjectName("KeyVowsTableWidget")
        self.KeyVowsTableWidget.setColumnCount(3)
        self.KeyVowsTableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KeyVowsTableWidget.setItem(6, 0, item)
        self.groupBox_6 = QtWidgets.QGroupBox(self.KeyTab)
        self.groupBox_6.setGeometry(QtCore.QRect(670, 0, 171, 421))
        self.groupBox_6.setObjectName("groupBox_6")
        self.KeySheetTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.KeySheetTextEdit.setGeometry(QtCore.QRect(10, 20, 151, 391))
        self.KeySheetTextEdit.setReadOnly(True)
        self.KeySheetTextEdit.setObjectName("KeySheetTextEdit")
        self.tabWidget.addTab(self.KeyTab, "")
        self.CipherTab = QtWidgets.QWidget()
        self.CipherTab.setObjectName("CipherTab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.CipherTab)
        self.groupBox_7.setGeometry(QtCore.QRect(330, 0, 341, 421))
        self.groupBox_7.setObjectName("groupBox_7")
        self.CipherConsTableWidget = QtWidgets.QTableWidget(self.groupBox_7)
        self.CipherConsTableWidget.setGeometry(QtCore.QRect(10, 20, 321, 391))
        self.CipherConsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.CipherConsTableWidget.setObjectName("CipherConsTableWidget")
        self.CipherConsTableWidget.setColumnCount(3)
        self.CipherConsTableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherConsTableWidget.setItem(11, 2, item)
        self.CipherConsTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.groupBox_9 = QtWidgets.QGroupBox(self.CipherTab)
        self.groupBox_9.setGeometry(QtCore.QRect(670, 0, 171, 421))
        self.groupBox_9.setObjectName("groupBox_9")
        self.CipherSheetTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_9)
        self.CipherSheetTextEdit.setGeometry(QtCore.QRect(10, 20, 151, 391))
        self.CipherSheetTextEdit.setReadOnly(True)
        self.CipherSheetTextEdit.setObjectName("CipherSheetTextEdit")
        self.groupBox_8 = QtWidgets.QGroupBox(self.CipherTab)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 150, 331, 271))
        self.groupBox_8.setObjectName("groupBox_8")
        self.CipherVowsTableWidget = QtWidgets.QTableWidget(self.groupBox_8)
        self.CipherVowsTableWidget.setGeometry(QtCore.QRect(10, 20, 311, 241))
        self.CipherVowsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.CipherVowsTableWidget.setObjectName("CipherVowsTableWidget")
        self.CipherVowsTableWidget.setColumnCount(3)
        self.CipherVowsTableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CipherVowsTableWidget.setItem(6, 1, item)
        self.CipherVowsTableWidget.horizontalHeader().setDefaultSectionSize(98)
        self.CipherVowsTableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.CipherDesc = QtWidgets.QTextBrowser(self.CipherTab)
        self.CipherDesc.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.CipherDesc.setObjectName("CipherDesc")
        self.tabWidget.addTab(self.CipherTab, "")
        self.BaseTab = QtWidgets.QWidget()
        self.BaseTab.setObjectName("BaseTab")
        self.BaseDesc = QtWidgets.QTextBrowser(self.BaseTab)
        self.BaseDesc.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.BaseDesc.setObjectName("BaseDesc")
        self.groupBox_11 = QtWidgets.QGroupBox(self.BaseTab)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 150, 331, 271))
        self.groupBox_11.setObjectName("groupBox_11")
        self.BaseVowsTableWidget = QtWidgets.QTableWidget(self.groupBox_11)
        self.BaseVowsTableWidget.setGeometry(QtCore.QRect(10, 20, 311, 241))
        self.BaseVowsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.BaseVowsTableWidget.setObjectName("BaseVowsTableWidget")
        self.BaseVowsTableWidget.setColumnCount(3)
        self.BaseVowsTableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseVowsTableWidget.setItem(6, 1, item)
        self.groupBox_10 = QtWidgets.QGroupBox(self.BaseTab)
        self.groupBox_10.setGeometry(QtCore.QRect(330, 0, 341, 421))
        self.groupBox_10.setObjectName("groupBox_10")
        self.BaseConsTableWidget = QtWidgets.QTableWidget(self.groupBox_10)
        self.BaseConsTableWidget.setGeometry(QtCore.QRect(10, 20, 321, 391))
        self.BaseConsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.BaseConsTableWidget.setObjectName("BaseConsTableWidget")
        self.BaseConsTableWidget.setColumnCount(3)
        self.BaseConsTableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BaseConsTableWidget.setItem(11, 2, item)
        self.groupBox_12 = QtWidgets.QGroupBox(self.BaseTab)
        self.groupBox_12.setGeometry(QtCore.QRect(670, 0, 171, 421))
        self.groupBox_12.setObjectName("groupBox_12")
        self.BaseSheetTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_12)
        self.BaseSheetTextEdit.setGeometry(QtCore.QRect(10, 20, 151, 391))
        self.BaseSheetTextEdit.setReadOnly(True)
        self.BaseSheetTextEdit.setObjectName("BaseSheetTextEdit")
        self.tabWidget.addTab(self.BaseTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(CiphersDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(CiphersDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(CiphersDialog.accept)
        self.buttonBox.rejected.connect(CiphersDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CiphersDialog)

    def retranslateUi(self, CiphersDialog):
        _translate = QtCore.QCoreApplication.translate
        CiphersDialog.setWindowTitle(_translate("CiphersDialog", "Ciphers"))
        self.groupBox_1.setTitle(_translate("CiphersDialog", "Consonants"))
        __sortingEnabled = self.IPAConsTableWidget.isSortingEnabled()
        self.IPAConsTableWidget.setSortingEnabled(False)
        item = self.IPAConsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "p"))
        item = self.IPAConsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "b"))
        item = self.IPAConsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "t"))
        item = self.IPAConsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "d"))
        item = self.IPAConsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "k"))
        item = self.IPAConsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "g"))
        item = self.IPAConsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "θ"))
        item = self.IPAConsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "ð"))
        item = self.IPAConsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "f"))
        item = self.IPAConsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "v"))
        item = self.IPAConsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "s"))
        item = self.IPAConsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "z"))
        item = self.IPAConsTableWidget.item(5, 2)
        item.setText(_translate("CiphersDialog", "ʦ"))
        item = self.IPAConsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "ʃ"))
        item = self.IPAConsTableWidget.item(6, 1)
        item.setText(_translate("CiphersDialog", "ʒ"))
        item = self.IPAConsTableWidget.item(7, 0)
        item.setText(_translate("CiphersDialog", "ʧ"))
        item = self.IPAConsTableWidget.item(7, 1)
        item.setText(_translate("CiphersDialog", "ʤ"))
        item = self.IPAConsTableWidget.item(8, 0)
        item.setText(_translate("CiphersDialog", "h"))
        item = self.IPAConsTableWidget.item(8, 1)
        item.setText(_translate("CiphersDialog", "x"))
        item = self.IPAConsTableWidget.item(8, 2)
        item.setText(_translate("CiphersDialog", "ɲ"))
        item = self.IPAConsTableWidget.item(9, 0)
        item.setText(_translate("CiphersDialog", "n"))
        item = self.IPAConsTableWidget.item(9, 1)
        item.setText(_translate("CiphersDialog", "m"))
        item = self.IPAConsTableWidget.item(9, 2)
        item.setText(_translate("CiphersDialog", "ŋ"))
        item = self.IPAConsTableWidget.item(10, 0)
        item.setText(_translate("CiphersDialog", "l"))
        item = self.IPAConsTableWidget.item(10, 1)
        item.setText(_translate("CiphersDialog", "ɹ"))
        item = self.IPAConsTableWidget.item(10, 2)
        item.setText(_translate("CiphersDialog", "r"))
        item = self.IPAConsTableWidget.item(11, 0)
        item.setText(_translate("CiphersDialog", "ʔ"))
        item = self.IPAConsTableWidget.item(11, 1)
        item.setText(_translate("CiphersDialog", "j"))
        item = self.IPAConsTableWidget.item(11, 2)
        item.setText(_translate("CiphersDialog", "w"))
        self.IPAConsTableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("CiphersDialog", "Vowels"))
        __sortingEnabled = self.IPAVowsTableWidget.isSortingEnabled()
        self.IPAVowsTableWidget.setSortingEnabled(False)
        item = self.IPAVowsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "ɑ"))
        item = self.IPAVowsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "a"))
        item = self.IPAVowsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "ɪ"))
        item = self.IPAVowsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "i"))
        item = self.IPAVowsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "ʊ"))
        item = self.IPAVowsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "u"))
        item = self.IPAVowsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "ɛ"))
        item = self.IPAVowsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "e"))
        item = self.IPAVowsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "o"))
        item = self.IPAVowsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "ɔ"))
        item = self.IPAVowsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "ə"))
        item = self.IPAVowsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "ʌ"))
        item = self.IPAVowsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "æ"))
        self.IPAVowsTableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("CiphersDialog", "Raw Sheet"))
        self.IPASheetTextEdit.setPlainText(_translate("CiphersDialog", "ipa_sheet = {\n"
"    \'title\': \'IPA\',\n"
"    \'consonants\':\n"
"    [\n"
"    \'p\',\'b\',\'\',\n"
"    \'t\',\'d\',\'\',\n"
"    \'k\',\'g\',\'\',\n"
"    \'θ\',\'ð\',\'\',\n"
"    \'f\',\'v\',\'\',\n"
"    \'s\',\'z\',\'ʦ\',\n"
"    \'ʃ\',\'ʒ\',\'\',\n"
"    \'ʧ\',\'ʤ\',\'\',\n"
"    \'h\',\'x\',\'ɲ\',\n"
"    \'n\',\'m\',\'ŋ\',\n"
"    \'l\',\'ɹ\',\'r\',\n"
"    \'ʔ\',\'j\',\'w\'\n"
"    ],\n"
"    \'vowels\':\n"
"    [\n"
"    \'ɑ\',\'a\',\'\',\n"
"    \'ɪ\',\'i\',\'\',\n"
"    \'ʊ\',\'u\',\'\',\n"
"    \'ɛ\',\'e\',\'\',\n"
"    \'o\',\'ɔ\',\'\',\n"
"    \'ə\',\'ʌ\',\'\',\n"
"    \'æ\',\'\',\'\'\n"
"    ]\n"
"}"))
        self.IPADesc.setHtml(_translate("CiphersDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">These are the selected IPA phonemes, from which the other 3 default sheets are derived. Every transliterate standardizes input to this sheet, and then converts from this to the desired sheet. Syllable separation also works with this sheet. The default of defaults.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IPATab), _translate("CiphersDialog", "IPA"))
        self.groupBox_4.setTitle(_translate("CiphersDialog", "Consonants"))
        __sortingEnabled = self.KeyConsTableWidget.isSortingEnabled()
        self.KeyConsTableWidget.setSortingEnabled(False)
        item = self.KeyConsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "9"))
        item = self.KeyConsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "b"))
        item = self.KeyConsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "1"))
        item = self.KeyConsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "d"))
        item = self.KeyConsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "7"))
        item = self.KeyConsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "g"))
        item = self.KeyConsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "f"))
        item = self.KeyConsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "t"))
        item = self.KeyConsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "8"))
        item = self.KeyConsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "v"))
        item = self.KeyConsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "0"))
        item = self.KeyConsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "z"))
        item = self.KeyConsTableWidget.item(5, 2)
        item.setText(_translate("CiphersDialog", "c"))
        item = self.KeyConsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "q"))
        item = self.KeyConsTableWidget.item(6, 1)
        item.setText(_translate("CiphersDialog", "p"))
        item = self.KeyConsTableWidget.item(7, 0)
        item.setText(_translate("CiphersDialog", "6"))
        item = self.KeyConsTableWidget.item(7, 1)
        item.setText(_translate("CiphersDialog", "j"))
        item = self.KeyConsTableWidget.item(8, 0)
        item.setText(_translate("CiphersDialog", "h"))
        item = self.KeyConsTableWidget.item(8, 1)
        item.setText(_translate("CiphersDialog", "k"))
        item = self.KeyConsTableWidget.item(8, 2)
        item.setText(_translate("CiphersDialog", "m"))
        item = self.KeyConsTableWidget.item(9, 0)
        item.setText(_translate("CiphersDialog", "2"))
        item = self.KeyConsTableWidget.item(9, 1)
        item.setText(_translate("CiphersDialog", "3"))
        item = self.KeyConsTableWidget.item(9, 2)
        item.setText(_translate("CiphersDialog", "n"))
        item = self.KeyConsTableWidget.item(10, 0)
        item.setText(_translate("CiphersDialog", "5"))
        item = self.KeyConsTableWidget.item(10, 1)
        item.setText(_translate("CiphersDialog", "4"))
        item = self.KeyConsTableWidget.item(10, 2)
        item.setText(_translate("CiphersDialog", "r"))
        item = self.KeyConsTableWidget.item(11, 0)
        item.setText(_translate("CiphersDialog", "l"))
        item = self.KeyConsTableWidget.item(11, 1)
        item.setText(_translate("CiphersDialog", "y"))
        item = self.KeyConsTableWidget.item(11, 2)
        item.setText(_translate("CiphersDialog", "w"))
        self.KeyConsTableWidget.setSortingEnabled(__sortingEnabled)
        self.KeyDesc.setHtml(_translate("CiphersDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Key is a one-to-one alphanumeric representation of the selected IPA sounds. A single symbol for every phoneme. Incidentally, the numbers 0-9 are mapped according to the mnemonic major system. The custom font Keyform is for this sheet.</p></body></html>"))
        self.groupBox_5.setTitle(_translate("CiphersDialog", "Vowels"))
        __sortingEnabled = self.KeyVowsTableWidget.isSortingEnabled()
        self.KeyVowsTableWidget.setSortingEnabled(False)
        item = self.KeyVowsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "a"))
        item = self.KeyVowsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "&"))
        item = self.KeyVowsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "i"))
        item = self.KeyVowsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "#"))
        item = self.KeyVowsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "u"))
        item = self.KeyVowsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "$"))
        item = self.KeyVowsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "e"))
        item = self.KeyVowsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "%"))
        item = self.KeyVowsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "o"))
        item = self.KeyVowsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "@"))
        item = self.KeyVowsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "x"))
        item = self.KeyVowsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "="))
        item = self.KeyVowsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "s"))
        self.KeyVowsTableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_6.setTitle(_translate("CiphersDialog", "Raw Sheet"))
        self.KeySheetTextEdit.setPlainText(_translate("CiphersDialog", "key_sheet = {\n"
"    \'title\' : \'Key\',\n"
"    \'consonants\':\n"
"    [\n"
"    \'9\',\'b\',\'\',\n"
"    \'1\',\'d\',\'\',\n"
"    \'7\',\'g\',\'\',\n"
"    \'f\',\'t\',\'\',\n"
"    \'8\',\'v\',\'\',\n"
"    \'0\',\'z\',\'c\',\n"
"    \'q\',\'p\',\'\',\n"
"    \'6\',\'j\',\'\',\n"
"    \'h\',\'k\',\'m\',\n"
"    \'2\',\'3\',\'n\',\n"
"    \'5\',\'4\',\'r\',\n"
"    \'l\',\'y\',\'w\'\n"
"    ],\n"
"    \'vowels\':\n"
"    [\n"
"    \'a\',\'&\',\'\',\n"
"    \'i\',\'#\',\'\',\n"
"    \'u\',\'$\',\'\',\n"
"    \'e\',\'%\',\'\',\n"
"    \'o\',\'@\',\'\',\n"
"    \'x\',\'=\',\'\',\n"
"    \'s\',\'\',\'\'\n"
"    ]\n"
"}"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.KeyTab), _translate("CiphersDialog", "Key"))
        self.groupBox_7.setTitle(_translate("CiphersDialog", "Consonants"))
        item = self.CipherConsTableWidget.verticalHeaderItem(0)
        item.setText(_translate("CiphersDialog", "b"))
        item = self.CipherConsTableWidget.verticalHeaderItem(1)
        item.setText(_translate("CiphersDialog", "d"))
        item = self.CipherConsTableWidget.verticalHeaderItem(2)
        item.setText(_translate("CiphersDialog", "g"))
        item = self.CipherConsTableWidget.verticalHeaderItem(3)
        item.setText(_translate("CiphersDialog", "t"))
        item = self.CipherConsTableWidget.verticalHeaderItem(4)
        item.setText(_translate("CiphersDialog", "p"))
        item = self.CipherConsTableWidget.verticalHeaderItem(5)
        item.setText(_translate("CiphersDialog", "c"))
        item = self.CipherConsTableWidget.verticalHeaderItem(6)
        item.setText(_translate("CiphersDialog", "k"))
        item = self.CipherConsTableWidget.verticalHeaderItem(7)
        item.setText(_translate("CiphersDialog", "q"))
        item = self.CipherConsTableWidget.verticalHeaderItem(8)
        item.setText(_translate("CiphersDialog", "h"))
        item = self.CipherConsTableWidget.verticalHeaderItem(9)
        item.setText(_translate("CiphersDialog", "m"))
        item = self.CipherConsTableWidget.verticalHeaderItem(10)
        item.setText(_translate("CiphersDialog", "r"))
        item = self.CipherConsTableWidget.verticalHeaderItem(11)
        item.setText(_translate("CiphersDialog", "w"))
        item = self.CipherConsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CiphersDialog", "f"))
        item = self.CipherConsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CiphersDialog", "n"))
        __sortingEnabled = self.CipherConsTableWidget.isSortingEnabled()
        self.CipherConsTableWidget.setSortingEnabled(False)
        item = self.CipherConsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "b"))
        item = self.CipherConsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "bf"))
        item = self.CipherConsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "d"))
        item = self.CipherConsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "df"))
        item = self.CipherConsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "g"))
        item = self.CipherConsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "gf"))
        item = self.CipherConsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "t"))
        item = self.CipherConsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "tf"))
        item = self.CipherConsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "p"))
        item = self.CipherConsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "pf"))
        item = self.CipherConsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "c"))
        item = self.CipherConsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "cf"))
        item = self.CipherConsTableWidget.item(5, 2)
        item.setText(_translate("CiphersDialog", "cn"))
        item = self.CipherConsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "k"))
        item = self.CipherConsTableWidget.item(6, 1)
        item.setText(_translate("CiphersDialog", "kf"))
        item = self.CipherConsTableWidget.item(7, 0)
        item.setText(_translate("CiphersDialog", "q"))
        item = self.CipherConsTableWidget.item(7, 1)
        item.setText(_translate("CiphersDialog", "qf"))
        item = self.CipherConsTableWidget.item(8, 0)
        item.setText(_translate("CiphersDialog", "h"))
        item = self.CipherConsTableWidget.item(8, 1)
        item.setText(_translate("CiphersDialog", "hf"))
        item = self.CipherConsTableWidget.item(8, 2)
        item.setText(_translate("CiphersDialog", "hn"))
        item = self.CipherConsTableWidget.item(9, 0)
        item.setText(_translate("CiphersDialog", "m"))
        item = self.CipherConsTableWidget.item(9, 1)
        item.setText(_translate("CiphersDialog", "mf"))
        item = self.CipherConsTableWidget.item(9, 2)
        item.setText(_translate("CiphersDialog", "mn"))
        item = self.CipherConsTableWidget.item(10, 0)
        item.setText(_translate("CiphersDialog", "r"))
        item = self.CipherConsTableWidget.item(10, 1)
        item.setText(_translate("CiphersDialog", "rf"))
        item = self.CipherConsTableWidget.item(10, 2)
        item.setText(_translate("CiphersDialog", "rn"))
        item = self.CipherConsTableWidget.item(11, 0)
        item.setText(_translate("CiphersDialog", "w"))
        item = self.CipherConsTableWidget.item(11, 1)
        item.setText(_translate("CiphersDialog", "wf"))
        item = self.CipherConsTableWidget.item(11, 2)
        item.setText(_translate("CiphersDialog", "wn"))
        self.CipherConsTableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_9.setTitle(_translate("CiphersDialog", "Raw Sheet"))
        self.CipherSheetTextEdit.setPlainText(_translate("CiphersDialog", "cipher_sheet = {\n"
"    \'title\' : \'Cipher\',\n"
"    \'consonants\':\n"
"    [\n"
"    \'b\',\'bf\',\'\',\n"
"    \'d\',\'df\',\'\',\n"
"    \'g\',\'gf\',\'\',\n"
"    \'t\',\'tf\',\'\',\n"
"    \'p\',\'pf\',\'\',\n"
"    \'c\',\'cf\',\'cn\',\n"
"    \'k\',\'kf\',\'\',\n"
"    \'q\',\'qf\',\'\',\n"
"    \'h\',\'hf\',\'hn\',\n"
"    \'m\',\'mf\',\'mn\',\n"
"    \'r\',\'rf\',\'rn\',\n"
"    \'w\',\'wf\',\'wn\'\n"
"    ],\n"
"    \'vowels\' :\n"
"    [\n"
"    \'l\',\'lf\',\'\',\n"
"    \'j\',\'jf\',\'\',\n"
"    \'y\',\'yf\',\'\',\n"
"    \'z\',\'zf\',\'\',\n"
"    \'v\',\'vf\',\'\',\n"
"    \'x\',\'xf\',\'\',\n"
"    \'s\',\'\',\'\'\n"
"    ]\n"
"}"))
        self.groupBox_8.setTitle(_translate("CiphersDialog", "Vowels"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(0)
        item.setText(_translate("CiphersDialog", "l"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(1)
        item.setText(_translate("CiphersDialog", "j"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(2)
        item.setText(_translate("CiphersDialog", "y"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(3)
        item.setText(_translate("CiphersDialog", "z"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(4)
        item.setText(_translate("CiphersDialog", "v"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(5)
        item.setText(_translate("CiphersDialog", "x"))
        item = self.CipherVowsTableWidget.verticalHeaderItem(6)
        item.setText(_translate("CiphersDialog", "s"))
        item = self.CipherVowsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CiphersDialog", "f"))
        item = self.CipherVowsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CiphersDialog", "n"))
        __sortingEnabled = self.CipherVowsTableWidget.isSortingEnabled()
        self.CipherVowsTableWidget.setSortingEnabled(False)
        item = self.CipherVowsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "l"))
        item = self.CipherVowsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "lf"))
        item = self.CipherVowsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "j"))
        item = self.CipherVowsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "jf"))
        item = self.CipherVowsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "y"))
        item = self.CipherVowsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "yf"))
        item = self.CipherVowsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "z"))
        item = self.CipherVowsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "zf"))
        item = self.CipherVowsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "v"))
        item = self.CipherVowsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "vf"))
        item = self.CipherVowsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "x"))
        item = self.CipherVowsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "xf"))
        item = self.CipherVowsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "s"))
        item = self.CipherVowsTableWidget.item(6, 1)
        item.setText(_translate("CiphersDialog", "sf"))
        self.CipherVowsTableWidget.setSortingEnabled(__sortingEnabled)
        self.CipherDesc.setHtml(_translate("CiphersDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cipher is the distinct system of base symbols and modifiers. Capitalization can work, but it doesn\'t, for compatibility with the other sheets. This uses all the consonant symbols in the Latin alphabet, and no vowels, to further obscure the phonetics. This is the only \'cipher\' in the default sheets.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CipherTab), _translate("CiphersDialog", "Cipher"))
        self.BaseDesc.setHtml(_translate("CiphersDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Base is a one-to-one representation of IPA, like Key, but prioritizes readability rather than conciseness. This only uses alphabetical characters and brackets. Very easy to pronounce.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_11.setTitle(_translate("CiphersDialog", "Vowels"))
        __sortingEnabled = self.BaseVowsTableWidget.isSortingEnabled()
        self.BaseVowsTableWidget.setSortingEnabled(False)
        item = self.BaseVowsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "a"))
        item = self.BaseVowsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "(aa)"))
        item = self.BaseVowsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "i"))
        item = self.BaseVowsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "(ii)"))
        item = self.BaseVowsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "u"))
        item = self.BaseVowsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "(oo)"))
        item = self.BaseVowsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "e"))
        item = self.BaseVowsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "(ee)"))
        item = self.BaseVowsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "o"))
        item = self.BaseVowsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "(aw)"))
        item = self.BaseVowsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "(uh)"))
        item = self.BaseVowsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "(ah)"))
        item = self.BaseVowsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "(ea)"))
        self.BaseVowsTableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_10.setTitle(_translate("CiphersDialog", "Consonants"))
        __sortingEnabled = self.BaseConsTableWidget.isSortingEnabled()
        self.BaseConsTableWidget.setSortingEnabled(False)
        item = self.BaseConsTableWidget.item(0, 0)
        item.setText(_translate("CiphersDialog", "p"))
        item = self.BaseConsTableWidget.item(0, 1)
        item.setText(_translate("CiphersDialog", "b"))
        item = self.BaseConsTableWidget.item(1, 0)
        item.setText(_translate("CiphersDialog", "t"))
        item = self.BaseConsTableWidget.item(1, 1)
        item.setText(_translate("CiphersDialog", "d"))
        item = self.BaseConsTableWidget.item(2, 0)
        item.setText(_translate("CiphersDialog", "k"))
        item = self.BaseConsTableWidget.item(2, 1)
        item.setText(_translate("CiphersDialog", "g"))
        item = self.BaseConsTableWidget.item(3, 0)
        item.setText(_translate("CiphersDialog", "(th)"))
        item = self.BaseConsTableWidget.item(3, 1)
        item.setText(_translate("CiphersDialog", "(dth)"))
        item = self.BaseConsTableWidget.item(4, 0)
        item.setText(_translate("CiphersDialog", "f"))
        item = self.BaseConsTableWidget.item(4, 1)
        item.setText(_translate("CiphersDialog", "v"))
        item = self.BaseConsTableWidget.item(5, 0)
        item.setText(_translate("CiphersDialog", "s"))
        item = self.BaseConsTableWidget.item(5, 1)
        item.setText(_translate("CiphersDialog", "z"))
        item = self.BaseConsTableWidget.item(5, 2)
        item.setText(_translate("CiphersDialog", "(ts)"))
        item = self.BaseConsTableWidget.item(6, 0)
        item.setText(_translate("CiphersDialog", "(sh)"))
        item = self.BaseConsTableWidget.item(6, 1)
        item.setText(_translate("CiphersDialog", "(jh)"))
        item = self.BaseConsTableWidget.item(7, 0)
        item.setText(_translate("CiphersDialog", "(ch)"))
        item = self.BaseConsTableWidget.item(7, 1)
        item.setText(_translate("CiphersDialog", "j"))
        item = self.BaseConsTableWidget.item(8, 0)
        item.setText(_translate("CiphersDialog", "h"))
        item = self.BaseConsTableWidget.item(8, 1)
        item.setText(_translate("CiphersDialog", "(kh)"))
        item = self.BaseConsTableWidget.item(8, 2)
        item.setText(_translate("CiphersDialog", "(ny)"))
        item = self.BaseConsTableWidget.item(9, 0)
        item.setText(_translate("CiphersDialog", "n"))
        item = self.BaseConsTableWidget.item(9, 1)
        item.setText(_translate("CiphersDialog", "m"))
        item = self.BaseConsTableWidget.item(9, 2)
        item.setText(_translate("CiphersDialog", "(ng)"))
        item = self.BaseConsTableWidget.item(10, 0)
        item.setText(_translate("CiphersDialog", "l"))
        item = self.BaseConsTableWidget.item(10, 1)
        item.setText(_translate("CiphersDialog", "r"))
        item = self.BaseConsTableWidget.item(10, 2)
        item.setText(_translate("CiphersDialog", "(rr)"))
        item = self.BaseConsTableWidget.item(11, 0)
        item.setText(_translate("CiphersDialog", "(-)"))
        item = self.BaseConsTableWidget.item(11, 1)
        item.setText(_translate("CiphersDialog", "y"))
        item = self.BaseConsTableWidget.item(11, 2)
        item.setText(_translate("CiphersDialog", "w"))
        self.BaseConsTableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_12.setTitle(_translate("CiphersDialog", "Raw Sheet"))
        self.BaseSheetTextEdit.setPlainText(_translate("CiphersDialog", "base_sheet = {\n"
"    \'title\' : \'Base\',\n"
"    \'consonants\':\n"
"    [\n"
"    \'p\',\'b\',\'\',\n"
"    \'t\',\'d\',\'\',\n"
"    \'k\',\'g\',\'\',\n"
"    \'(th)\',\'(dth)\',\'\',\n"
"    \'f\',\'v\',\'\',\n"
"    \'s\',\'z\',\'(ts)\',\n"
"    \'(sh)\',\'(jh)\',\'\',\n"
"    \'(ch)\',\'j\',\'\',\n"
"    \'h\',\'(kh)\',\'(ny)\',\n"
"    \'n\',\'m\',\'(ng)\',\n"
"    \'l\',\'r\',\'(rr)\',\n"
"    \'(-)\',\'y\',\'w\'\n"
"    ],\n"
"    \'vowels\':\n"
"    [\n"
"    \'a\',\'(aa)\',\'\',\n"
"    \'i\',\'(ii)\',\'\',\n"
"    \'u\',\'(oo)\',\'\',\n"
"    \'e\',\'(ee)\',\'\',\n"
"    \'o\',\'(aw)\',\'\',\n"
"    \'(uh)\',\'(ah)\',\'\',\n"
"    \'(ea)\',\'\',\'\'\n"
"    ]\n"
"}"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BaseTab), _translate("CiphersDialog", "Base"))
        self.label.setText(_translate("CiphersDialog", "This is ugly hard-coded documentation"))

