# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CiferoMain(object):
    def setupUi(self, CiferoMain):
        CiferoMain.setObjectName("CiferoMain")
        CiferoMain.resize(429, 293)
        self.centralWidget = QtWidgets.QWidget(CiferoMain)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.OutputModeCombo = QtWidgets.QComboBox(self.centralWidget)
        self.OutputModeCombo.setObjectName("OutputModeCombo")
        self.gridLayout_2.addWidget(self.OutputModeCombo, 0, 3, 1, 1)
        self.InputModeCombo = QtWidgets.QComboBox(self.centralWidget)
        self.InputModeCombo.setObjectName("InputModeCombo")
        self.gridLayout_2.addWidget(self.InputModeCombo, 0, 0, 1, 1)
        self.CiphersButton = QtWidgets.QPushButton(self.centralWidget)
        self.CiphersButton.setObjectName("CiphersButton")
        self.gridLayout_2.addWidget(self.CiphersButton, 7, 3, 1, 1)
        self.QuitButton = QtWidgets.QPushButton(self.centralWidget)
        self.QuitButton.setObjectName("QuitButton")
        self.gridLayout_2.addWidget(self.QuitButton, 7, 2, 1, 1)
        self.CentraButtonArea = QtWidgets.QVBoxLayout()
        self.CentraButtonArea.setSpacing(6)
        self.CentraButtonArea.setObjectName("CentraButtonArea")
        self.SwapButton = QtWidgets.QPushButton(self.centralWidget)
        self.SwapButton.setObjectName("SwapButton")
        self.CentraButtonArea.addWidget(self.SwapButton)
        self.RawTransliterateButton = QtWidgets.QPushButton(self.centralWidget)
        self.RawTransliterateButton.setObjectName("RawTransliterateButton")
        self.CentraButtonArea.addWidget(self.RawTransliterateButton)
        self.StripButton = QtWidgets.QPushButton(self.centralWidget)
        self.StripButton.setObjectName("StripButton")
        self.CentraButtonArea.addWidget(self.StripButton)
        self.PasteButton = QtWidgets.QPushButton(self.centralWidget)
        self.PasteButton.setObjectName("PasteButton")
        self.CentraButtonArea.addWidget(self.PasteButton)
        self.CopyButton = QtWidgets.QPushButton(self.centralWidget)
        self.CopyButton.setObjectName("CopyButton")
        self.CentraButtonArea.addWidget(self.CopyButton)
        self.ClearButton = QtWidgets.QPushButton(self.centralWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.CentraButtonArea.addWidget(self.ClearButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.CentraButtonArea.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.CentraButtonArea, 2, 2, 1, 1)
        self.SettingsButton = QtWidgets.QPushButton(self.centralWidget)
        self.SettingsButton.setObjectName("SettingsButton")
        self.gridLayout_2.addWidget(self.SettingsButton, 7, 0, 1, 1)
        self.TransliterateButton = QtWidgets.QPushButton(self.centralWidget)
        self.TransliterateButton.setObjectName("TransliterateButton")
        self.gridLayout_2.addWidget(self.TransliterateButton, 0, 2, 1, 1)
        self.OutputTextEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.OutputTextEdit.setObjectName("OutputTextEdit")
        self.gridLayout_2.addWidget(self.OutputTextEdit, 2, 3, 1, 1)
        self.InputTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.InputTextEdit.setObjectName("InputTextEdit")
        self.gridLayout_2.addWidget(self.InputTextEdit, 2, 0, 1, 1)
        CiferoMain.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(CiferoMain)
        self.statusBar.setObjectName("statusBar")
        CiferoMain.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(CiferoMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 429, 21))
        self.menuBar.setObjectName("menuBar")
        CiferoMain.setMenuBar(self.menuBar)

        self.retranslateUi(CiferoMain)
        QtCore.QMetaObject.connectSlotsByName(CiferoMain)

    def retranslateUi(self, CiferoMain):
        _translate = QtCore.QCoreApplication.translate
        CiferoMain.setWindowTitle(_translate("CiferoMain", "Cifero 1.0"))
        self.CiphersButton.setText(_translate("CiferoMain", "Ciphers"))
        self.QuitButton.setText(_translate("CiferoMain", "Quit"))
        self.SwapButton.setText(_translate("CiferoMain", "Swap"))
        self.RawTransliterateButton.setText(_translate("CiferoMain", "Raw >>"))
        self.StripButton.setText(_translate("CiferoMain", "Strip"))
        self.PasteButton.setText(_translate("CiferoMain", "Paste Input"))
        self.CopyButton.setText(_translate("CiferoMain", "Copy Output"))
        self.ClearButton.setText(_translate("CiferoMain", "Clear"))
        self.SettingsButton.setText(_translate("CiferoMain", "Settings"))
        self.TransliterateButton.setText(_translate("CiferoMain", ">>"))

